### ISSUE TITLE
Error "No Emails Found" for Adtech

### ISSUE THREAD

**Issue by danielindiano** [meumobi/AMS.Connect#40]
Check why this error occurs on adtech provider for the 'last day':

http://limitless-sea-32755.herokuapp.com/adtech

**Comment by elbidone** [comment]
This issue, and #42, are due to an invalid timezone configured on gmail account of amsconnect. The timezone of gmail account is based on your own timezone, last device tz that access the account. Reports are sent at 4am Date d on Paris but 11pm Date d-1 on Brasilia. It's why there's always an unexpected difference of one day.
I've changed the tz of my computer and open the amsconnect gmail account to change its tz to Paris. After that I've recalled adtech reports through ams.connect and now it works fine.

We should keep in mind this weakness and be careful to not access gmail account of ams.connect with different tz.
